version: '3.8'

services:
  dispatch-app:
    build: .
    ports:
      - "8501:8501"  # Streamlit
      - "5000:5000"  # MLflow
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
    restart: unless-stopped
