version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: dispatch_app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./src:/app/src
      - ./scripts:/app/scripts
    environment:
      - PYTHONUNBUFFERED=1
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    restart: unless-stopped

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: dispatch_mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlartifacts:/mlflow/mlartifacts
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    command: [
      "mlflow", "server",
      "--backend-store-uri", "/mlflow/mlruns",
      "--default-artifact-root", "/mlflow/mlartifacts",
      "--host", "0.0.0.0",
      "--port", "5000"
    ]
    restart: unless-stopped

