name: dispatch-monitoring-env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - opencv
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip:
      - torch==2.5.0
      - torchvision==0.20.0
      - ultralytics==8.0.170       # YOLOv8
      - deep_sort_realtime==1.3.1  # Object tracking
      - streamlit==1.35.0          # Feedback UI
      - mlflow==2.13.0             # Model tracking
      - tqdm
      - seaborn

